# Generated by Django 4.1.3 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.TextField(max_length=10, null=True)),
                ('long', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
