# Generated by Django 4.1.3 on 2022-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_namemodel_rename_long_mymodel_longmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='long',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='short',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='namemodel',
            name='mytext',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
